Capstone/Capstone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('companies/', include("companies.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Capstone/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_user_view, name="login_user_view"),
    path("register/", views.register_user_view, name="register_user_view"),
    path("logout/", views.logout_user_view, name="logout_user_view"),
    path('profile/<user_id>/', views.profile_page, name="profile_page"),
    path('profile/update/<user_id>/', views.update_profile_page, name="update_profile_page"),
    path('my_added_company/<user_id>/', views.added_company_list_view, name="added_company_list_view"),
]

Capstone/companies/urls.py
from django.urls import path
from . import views

app_name = "companies"

urlpatterns = [
     
    path("all/", views.all_companies_view, name="all_companies_view"),
    path("add/", views.add_company_view, name="add_company_view"),
    path("dashboard/<user_id>/",views.dashbord_view,name="dashbord_view"),
    path("update/<company_id>/", views.company_update_view, name="company_update_view"),
    path("delete/<company_id>/", views.company_delete_view, name="company_delete_view"),
    path("detail/<company_id>/", views.company_detail_view, name="company_detail_view"),
    path("search/",views.companies_search_view, name="companies_search_view"),
    path("approve/",views.approve_company_view, name="approve_company_view"),
    path("reveiw/add/<company_id>/",views.add_Review_view,name="add_Review_view"),
    path("reveiw/delete/<review_id>/",views.review_delete_view,name="review_delete_view"),
    path("reveiw/update/<review_id>/", views.review_update_view, name="review_update_view"),
    path("reveiw/all/", views.all_reveiws_view, name="all_reveiws_view"),
    path("favorite/add/<review_id>/", views.add_favorite_view, name="add_favorite_view"),
    path("favorite/delete/<review_id>/", views.remove_favorite_view, name="remove_favorite_view"),
    path("report/<review_id>/", views.report_view, name="report_view"),
    path("reports", views.all_report_view, name="all_report_view"),
    path("favorites/", views.user_favorite_view, name="user_favorite_view"),
    path("field/", views.company_filter_view, name="company_filter_view"),
    # path("reviews/filter/", views.review_filter_view, name="review_filter_view"),
]

Capstone/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('about/', views.about_view, name="about_view"),
    path('error/', views.not_found_view, name="not_found_view"),

]

Capstone/companies/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Company(models.Model):

    name = models.CharField(max_length=2048)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/")
    field = models.CharField(max_length=2048)
    info= models.TextField()
    description = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

   
    def __str__(self):
        return f"{self.name}"
    

class Review(models.Model):

    rating_choices = ((1, "1 Star"), (2, "2 Stars"), (3, "3 Stars"), (4, "4 Start"), (5, "5 Start"), )
    experience_choices = (("موظف", "موظف"), ("مقابلة", "مقابلة"), ("تدريب", "تدريب"), )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company=models.ForeignKey(Company,on_delete=models.CASCADE)
    experience = models.CharField(max_length=128, choices=experience_choices)
    position = models.CharField(max_length=256)
    description = models.TextField()
    publish_date = models.DateField(auto_now_add=True)
    rating = models.IntegerField(choices=rating_choices)



    def __str__(self):
        return f"{self.user.first_name} on {self.company.name}"

class Favorite(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.review} on {self.review}"

class Report(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.review} on {self.review}"

Capstone/companies/views.py
from django.shortcuts import render, redirect, resolve_url
from django.http import HttpRequest, HttpResponse

from django.contrib.auth.models import User
from accounts.models import Profile

from .models import Company, Favorite, Report,Review
from django.db.models import Count

# Create your views here.
def add_company_view(request: HttpRequest):
    try:
        msg= None
        if not request.user.is_authenticated:  
             return redirect("main:home_view")

        if request.method == "POST":
            if request.user.is_staff:  
                new_company = Company(user=request.user,name=request.POST["name"], field=request.POST["field"],info=request.POST["info"], description=request.POST["description"],image=request.FILES["image"],approved=True)
                new_company.save()
                msg='تم إضافة الشركة'
                url = resolve_url("companies:all_companies_view") + "?msg=" + msg
                return redirect(url)
            else:
                new_company = Company(user=request.user,name=request.POST["name"], field=request.POST["field"],info=request.POST["info"], description=request.POST["description"],image=request.FILES["image"])
                new_company.save()
                msg='تم طلب إضافة شركة'
                url = resolve_url("companies:all_companies_view") + "?msg=" + msg
                return redirect(url)

        return render(request, 'companies/add_company.html')
    except: 
        return redirect("main:not_found_view")

def dashbord_view(request: HttpRequest, user_id):
    try:
        profile = Profile.objects.get(user__id=user_id)
    except:
        return render(request, "main/not_found.html")


    return render(request, "companies/dashboard.html",{"profile" : profile})

def approve_company_view(request: HttpRequest):
    try:
        msg = None
        if not request.user.is_authenticated:  
             return redirect("main:home_view")

        companies = Company.objects.filter(approved=False)
        return render(request, "companies/approved_company.html", {"companies" : companies })
    except: 
        return redirect("main:not_found_view")


#updating company  
def company_update_view(request:HttpRequest, company_id):
    
    if not request.user.is_staff:
      return redirect("accounts:login_user_view")
    
    company = Company.objects.get(id=company_id)

    try:

        if request.method == "POST":
                company.name = request.POST["name"]
                company.field = request.POST["field"]
                company.info = request.POST["info"]
                company.description = request.POST["description"]
                if "image" in request.FILES:
                    company.image = request.FILES["image"]
                company.save()
                return redirect("companies:company_detail_view", company_id=company.id)
    except:
        return redirect("main:not_found_view")

    return render(request,"companies/update_company.html",{"company":company})

#deleting company from database
def company_delete_view(request: HttpRequest, company_id):
    try:

        if not request.user.is_staff:
            return redirect("accounts:login_user_view")
        
        company = Company.objects.get(id=company_id)
        company.delete()
        

        return redirect("companies:all_companies_view")
    except:
        return redirect("main:not_found_view")

def all_companies_view(request: HttpRequest):

    #companies = Company.objects.all()
    companies = Company.objects.filter(approved=True)
    
    return render(request, "companies/all_companies.html", {"companies" : companies})


def company_detail_view(request: HttpRequest, company_id):
    try:     
        company = Company.objects.get(id=company_id)
        reviews = Review.objects.filter(company=company)  
        # filter reviews
        for index, review in enumerate(reviews):
                reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
        if "experience" and "position" in request.GET:
                experience = request.GET.get("experience")
                position= request.GET.get("position")
                order= request.GET.get("order")
                if experience !="all" and position != "all":
                    if order != "all":
                        Review.objects.filter(company=company,experience=experience,position=position).order_by(f"-{order}")
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                    if order == "favorite": 
                        reviews_favorite = Review.objects.filter(company=company,experience=experience,position=position).annotate(favorite_count=Count('favorite'))
                        reviews = reviews_favorite.order_by('-favorite_count')
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                        return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                    else:
                        reviews = Review.objects.filter(company=company,experience=experience,position=position)
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                    return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                if experience =="all" and position != "all":
                    if order != "all":
                        reviews = Review.objects.filter(company=company,position=position).order_by(f"-{order}")
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                    if order == "favorite": 
                        reviews_favorite = Review.objects.filter(company=company,position=position).annotate(favorite_count=Count('favorite'))
                        reviews = reviews_favorite.order_by('-favorite_count')
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                        return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                    else:
                        reviews = Review.objects.filter(company=company,position=position)
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                    return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                if experience !="all" and position == "all":
                    if order != "all":
                        reviews = Review.objects.filter(company=company,experience=experience).order_by(f"-{order}")
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                    if order == "favorite": 
                        reviews_favorite = Review.objects.filter(company=company,experience=experience).annotate(favorite_count=Count('favorite'))
                        reviews = reviews_favorite.order_by('-favorite_count')
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                        return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                    else:
                        reviews = Review.objects.filter(company=company,experience=experience)
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                    return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                else:
                    if order != "all":
                        reviews = Review.objects.filter(company=company).order_by(f"-{order}")
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                        return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
                    if order == "favorite":
                        reviews_favorite = Review.objects.annotate(favorite_count=Count('favorite'))
                        reviews = reviews_favorite.order_by('-favorite_count')
                        for index, review in enumerate(reviews):
                            reviews[index].is_favored = Favorite.objects.filter(user=request.user, review=review).exists()
                        return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})
        # end filter reviews
        if request.method == "POST":
                if not request.user.is_staff:
                    return redirect("accounts:login_user_view")
                company.approved = request.POST["approved"]
                company.save()
                msg='تم الإضافة'
                return redirect("companies:all_companies_view")
        
        return render(request, "companies/company_detail.html", {"company" : company,"reviews" : reviews})

Capstone/companies/templates/companies/add_reveiw.html
{% extends 'main/base.html' %}


{% block title %} أضافة تعليق  {% endblock %}


{% block content %}
<style>

@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400");
@import url("https://fonts.googleapis.com/css?family=Playfair+Display");


.container-signup .form,
.container-signup form  {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}


body {
  direction: rtl;
}


.container-signup {
 margin-right: 20%;
  margin-top: 5%;
  padding: 10px;
  width: 800px;
  height: 600px;
  background: rgba(255, 255, 255, 0.195);
  position: relative;
  display: grid;
  box-shadow: 2px 2px 10px 0 rgba(51, 51, 51, 0.2);
  border-radius: 3%;
}



.container-signup .form--heading {
  font-size: 25px;
  height: 50px;
  color: #30334B;
  font-family: "Source Sans Pro", sans-serif;
}


.container-signup form  {
  width: 50%;
}
.container-signup form > * {
  margin: 10px;
}
.form-label {
    
    margin-left: 83% !important;
    margin-bottom: -5px !important;
    width: 75px;
}



.container-signup form input::placeholder {
  color: #333;
  font-size: 10px;
}
.container-signup form input:focus {
  outline: 0;
  border-bottom: 1px solid rgba(128, 155, 206, 0.7);
  transition: 0.6s all ease;
}

.container-signup .button {
  width: 50%;
  height: 30px;
  border: 0;
  outline: 0;
  color: white;
  font-size: 15px;
  font-weight: 400;
  position: relative;
  z-index: 3;
  background: #30334B;
  font-family: "Source Sans Pro", sans-serif;
  cursor: pointer;
}



</style>
<div class="container-signup">
   <div class="form form--signup ">
        <div class="form--heading"> إضافة تعليق</div>

        {% if request.user.is_authenticated %}

        <form action="{% url 'companies:add_Review_view' company.id %}" method="post" >
            {% csrf_token %}
        <label class="form-label" >نوع التجربه </label>
        <select name="experience" class="form-select" >
            {% for value, title in review.experience_choices %}
                <option value="{{value}}">{{title}}</option>
            {% endfor %}
        </select>
        <label class="form-label" >المنصب  </label>
        <input type="text" name="position" class="form-control">
        <label class="form-label"> الوصف </label>
        <textarea class="form-control" name="description"></textarea>
        <label class="form-label">قيم تجربتك</label>
                <div class="rate"style="color: #f9c448;">
                    <input type="radio" name="rating" id="rating5" value="5" /><label for="rating5" title="5" class="fa fa-star"> 5 </label>
                    <input type="radio" name="rating" id="rating4" value="4"/><label for="rating4" title="4" class="fa fa-star"> 4 </label>
                    <input type="radio" name="rating" id="rating3" value="3"/><label for="rating3" title="3" class="fa fa-star"> 3 </label>
                    <input type="radio" name="rating" id="rating2" value="2"/><label for="rating2" title="2" class="fa fa-star"> 2 </label>
                    <input type="radio" name="rating" id="rating1" value="1"/><label for="rating1" title="1" class="fa fa-star"> 1 </label>
                </div>
        
           <button class="button" type="submit"  >اضافة</button>
        </form>
        {% else %}

        <div class="p-4">
            <h5>To comment, Please <a href="{% url 'account:login_user_view' %}"class="text-decoration-none"style="color: #3a7020;">sign in</a> , or <a href="{% url 'account:register_user_view' %}" class="text-decoration-none"style="color: #3a7020;">sign up</a> </h5>
        </div>

        {% endif %}
   </div>
</div>



{% endblock %}

Capstone/companies/templates/companies/add_success.html
{% extends 'main/base.html' %}

{% block title %} Service Request Success {% endblock %}


{% block content %}

<div class="row">
    <div class="col">
        
        <div class="alert alert-success" role="alert">
            <h2>Request Submitted Successfully</h2>
        </div>
        <h6><a class="btn btn-primary text-decoration-none" href="{% url 'accounts:profile_page' %}">View My Profile</a></h6>
    </div>
</div>


{% endblock %}

Capstone/companies/templates/companies/company_detail.html
{% extends 'main/base.html' %}

{% block title %} Details {{ company.name }} {% endblock %}

{% block content %}
{% if "msg" in  request.GET %}

<div class="alert alert-dismissible fade show"
    style="background-color: rgb(92, 84, 112); color:  rgb(250, 240, 230);" role="alert">
    <strong>{{request.GET.msg}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

  <!-- d -->
  <div class="row  d-flex flex-column align-items-center justify-content-center pt-5 pb-4"
    style="background-color: rgba(70, 106, 139, 0.61); box-shadow: 0 6px 12px rgb(185, 180, 199); color:rgb(255, 255, 255) ;">
    <div class="col-10 pt-3">
        <h3 class="text-center">{{ company.name }}</h3>
        <hr />
        <div class="row">
          <div class="col-4  "><img src="{{ company.image.url }}" class="rounded-2 w-100" /></div>
          <div class="col-4">
          <p style="font-size: 24px;">  {{company.field}} </p>
          <p style="font-size: 16px;"> {{company.description}}</p>
        </div>
        <div class="text-center">
        {% if request.user.is_staff %}
                  <form action="{% url 'companies:company_detail_view' company.id %}" method="post">
                    {% csrf_token %}
                    <a href="{% url 'companies:company_update_view' company.id %}" class="btn" style="background-color: rgb(255, 255, 255); color:rgb(70, 106, 139) ;">تحديث</a>
                    <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#deleteModal"
                        style="background-color: rgb(255, 255, 255); color:rgb(70, 106, 139) ;">حذف</button>
                        {% endif %}
                        {% if company.approved == False %}
                    <button type="submit" name="approved" value=True class="btn"
                      style="background-color: rgb(255, 255, 255); color:rgb(70, 106, 139) ;">توثيق</button>
                      
                      {% endif %}
                    </form>
                </div>
    </div>
</div>

  <!-- d -->





</div>
<br>
<h2 class="pt-5">التجارب  </h2>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">حذف الشركة</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        هل انت متأكد من حذف    <span class="fw-bold">{{company.name}}</span> ؟
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">تراجع</button>
        <a href="{% url 'companies:company_delete_view' company.id %}" class="btn btn-danger">نعم ، حذف !</a>
      </div>
    </div>
  </div>
</div>

<!-- End  Modal -->


<!--company reviews-->
<hr />
<form action="{% url 'companies:company_detail_view' company.id %}" method="get">
<div class="row gap-2" dir="rtl">
  <select class="form-select" style="width: auto;" aria-label="Default select example" name="experience">
    <option value="all" >  تصفية حسب الخبرة </option>
    <option value="موظف" >  موظف </option>
    <option value="مقابلة"> مقابلة </option>
    <option value="تدريب"> تدريب </option>
</select>
<select class="form-select" style="width: auto;" aria-label="Default select example" name="position">
  <option value="all" >  تصفية حسب المنصب </option>
  <option value="مهندس برمجيات" > مهندس برمجيات</option>
  <option value="مدير تسويق"> مدير تسويق</option>
  <option value="مهندس معماري"> مهندس معماري </option>
</select>
<select class="form-select" style="width: auto;" aria-label="Default select example" name="order">
  <option value="all" >  ترتيب حسب </option>
  <option value="rating" > اعلى تقييم </option>
  <option value="favorite" > اعلى اعجاب </option>
  <option value="publish_date"> الاحدث</option>
</select>
<button type="submit" style="width: auto; background-color: rgb(70, 106, 139); color:rgb(255, 255, 255);" class="btn" >تطبيق التصفية</button>
</div>
</form>
<br>
<div class="mt-4">
  {% for review in reviews %}
  <div class="d-flex flex-column gap-1 border border-1 rounded p-4 mt-3">
    <div class="h4 pb-4 mb-4  border-bottom  fw-bold">
      {{review.user.username}}     {% if request.user.id == review.user.id or request.user.is_staff %}
      <div class="d-grid gap-2 d-md-block text-start ">
        <button class="btn btn-outline-danger" type="button"  data-bs-toggle="modal"
        data-bs-target="#deleteReviewModal{{review.id}}">حذف</button>
        <a href="{% url 'companies:review_update_view' review.id %}?id={{company.id}}" class="btn btn-outline-warning">تعديل </a>
      </div>
      {% endif %}
    </div>
    <h6 class="text-start">{{ review.publish_date }}</h6> 
    <p > نوع التجربه:{{review.experience}} </p>
    <h5 >{{ review.position }}</h5>
    <h6 class="pb-3">{{ review.description }}</h6>
    <div style="color: #f9c448;">
      {% if review.rating == 1 %}
      <span class="fa fa-star fa-2x"></span>
      {% elif review.rating == 2 %}
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      {% elif review.rating == 3 %}
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      {% elif review.rating == 4 %}
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      {% elif review.rating == 5 %}
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      <span class="fa fa-star fa-2x"></span>
      {% endif %} 
  </div>
  <h6 class="text-start"><a href="{% url 'companies:report_view' review.id  %}" class="text-danger "> 
    <span class="material-symbols-outlined">
      flag
      </span></a>
    <a href="{% if review.is_favored  %}{% url 'companies:remove_favorite_view' review.id  %}{% else %}{% url 'companies:add_favorite_view' review.id  %}{% endif %}"
      class="{% if review.is_favored %} text-danger {% endif%}"><span class=" material-symbols-outlined">favorite </span></a> {{ review.favorite_set.count }}
      </h6>

  </div>
  <!-- for reviw -->
  {% if request.user.id == review.user.id or request.user.is_staff %}
  <div class="modal fade" id="deleteReviewModal{{review.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">حذف تجربة</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          هل انت متأكد من حذف تجربتك في  <span class="fw-bold">{{company.name}}</span> ؟
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">تراجع</button>
          <a href="{% url 'companies:review_delete_view' review.id %}" class="btn btn-danger">نعم ، حذف !</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>

<div class="row justify-content-center">
  <div class="col-md-6 pt-5 text-center">
    {% if request.user.is_authenticated %}
    <a href="{% url 'companies:add_Review_view' company.id %}" class="btn btn-warning ">إضافة تجربة </a>


    {% else %}
    <div class="p-4">
      <h5> لإضافة تجربتك يرجى <a href="{% url 'accounts:login_user_view' %}">تسجيل الدخول</a> , او <a
          href="{% url 'accounts:register_user_view' %}">التسجيل</a> </h5>
    </div>

    {% endif %}
  </div>
</div>



{% endblock %}

Capstone/companies/templates/companies/update_review.html
{% extends 'main/base.html' %}



{% block title %} تحديث تعليق {% endblock %}


{% block content %}
<style>

@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400");
@import url("https://fonts.googleapis.com/css?family=Playfair+Display");


.container-signup .form,
.container-signup form  {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}


body {

  direction: rtl;
}


.container-signup {
 margin-right: 20%;
  margin-top: 5%;
  padding: 10px;
  width: 800px;
  height: 600px;
  background: rgba(255, 255, 255, 0.195);
  position: relative;
  display: grid;
  box-shadow: 2px 2px 10px 0 rgba(51, 51, 51, 0.2);
  border-radius: 3%; 
}



.container-signup .form--heading {
  font-size: 25px;
  height: 50px;
  color: #30334B;
  font-family: "Source Sans Pro", sans-serif;
}


.container-signup form  {
  width: 50%;
}
.container-signup form > * {
  margin: 10px;
}
.form-label {
    
    margin-left: 83% !important;
    margin-bottom: -5px !important;
    width: 65px;
}



.container-signup form input::placeholder {
  color: #333;
  font-size: 10px;
}
.container-signup form input:focus {
  outline: 0;
  border-bottom: 1px solid rgba(128, 155, 206, 0.7);
  transition: 0.6s all ease;
}

.container-signup .button {
  width: 50%;
  height: 30px;
  border: 0;
  outline: 0;
  color: white;
  font-size: 15px;
  font-weight: 400;
  position: relative;
  z-index: 3;
  background: #30334B;
  font-family: "Source Sans Pro", sans-serif;
  cursor: pointer;
}
.form-label {
    
    margin-left: 83% !important;
    margin-bottom: -5px !important;
    width: 75px;
}



</style>
<div class="container-signup">
   <div class="form form--signup ">
        <div class="form--heading"> تعديل تعليق</div>

        {% if request.user.is_authenticated %}

        <form action="{% url 'companies:review_update_view' review.id %}?id={{request.GET.id}}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <label class="form-label" >نوع التجربه </label>
        <select name="experience" class="form-select" >
            {% for value, title in review.experience_choices %}
                <option value="{{value}}" {% if review.Experience == value %} selected {% endif%}>{{title}}</option>
            {% endfor %}
        </select>
        <label class="form-label" >المنصب  </label>
        <input type="text" name="position" value="{{ review.position }}" class="form-control">
        <label class="form-label"> الوصف </label>
        <textarea class="form-control" name="description">{{ review.description }}</textarea>
        <label class="form-label">قيم تجربتك</label>
                <div class="rate"style="color: #f9c448;">
                    <input type="radio" name="rating" id="rating5" value="5"  {% if review.rating == 5 %} checked {% endif%}/><label for="rating5" title="5" class="fa fa-star"> 5 </label>
                    <input type="radio" name="rating" id="rating4" value="4" {% if review.rating == 4 %} checked {% endif%}/><label for="rating4" title="4" class="fa fa-star"> 4 </label>
                    <input type="radio" name="rating" id="rating3" value="3" {% if review.rating == 3 %} checked {% endif%}/><label for="rating3" title="3" class="fa fa-star"> 3 </label>
                    <input type="radio" name="rating" id="rating2" value="2"{% if review.rating == 2 %} checked {% endif%}/><label for="rating2" title="2" class="fa fa-star"> 2 </label>
                    <input type="radio" name="rating" id="rating1" value="1"{% if review.rating == 1 %} checked {% endif%}/><label for="rating1" title="1" class="fa fa-star"> 1 </label>
                </div>
        
           <button class="button" type="submit"  >تحديث</button>
        </form>
        {% else %}

        <div class="p-4">
            <h5>للتعليق يرجى <a href="{% url 'account:login_user_view' %}"class="text-decoration-none"style="color: #3a7020;">التسجيل </a> , او <a href="{% url 'account:register_user_view' %}" class="text-decoration-none"style="color: #3a7020;">تسجيل الدخول</a> </h5>
        </div>

        {% endif %}
   </div>
</div>



{% endblock %}