Capstone/Capstone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('companies/', include("companies.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Capstone/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_user_view, name="login_user_view"),
    path("register/", views.register_user_view, name="register_user_view"),
    path("logout/", views.logout_user_view, name="logout_user_view"),
    path('profile/<user_id>/', views.profile_page, name="profile_page"),
    path('profile/update/<user_id>/', views.update_profile_page, name="update_profile_page"),
    path('my_added_company/<user_id>/', views.added_company_list_view, name="added_company_list_view"),
]

Capstone/companies/urls.py
from django.urls import path
from . import views

app_name = "companies"

urlpatterns = [
     
    path("all/", views.all_companies_view, name="all_companies_view"),
    path("add/", views.add_company_view, name="add_company_view"),
    path("dashboard/<user_id>/",views.dashbord_view,name="dashbord_view"),
    path("update/<company_id>/", views.company_update_view, name="company_update_view"),
    path("delete/<company_id>/", views.company_delete_view, name="company_delete_view"),
    path("detail/<company_id>/", views.company_detail_view, name="company_detail_view"),
    path("search/",views.companies_search_view, name="companies_search_view"),
    path("approve/",views.approve_company_view, name="approve_company_view"),
    path("reveiw/add/<company_id>/",views.add_Review_view,name="add_Review_view"),
    path("reveiw/delete/<review_id>/",views.review_delete_view,name="review_delete_view"),
    path("reveiw/update/<review_id>/", views.review_update_view, name="review_update_view"),
    path("reveiw/all/", views.all_reveiws_view, name="all_reveiws_view"),
    path("favorite/add/<review_id>/", views.add_favorite_view, name="add_favorite_view"),
    path("favorite/delete/<review_id>/", views.remove_favorite_view, name="remove_favorite_view"),
    path("report/<review_id>/", views.report_view, name="report_view"),
    path("reports", views.all_report_view, name="all_report_view"),
    path("favorites/", views.user_favorite_view, name="user_favorite_view"),
    path("field/", views.company_filter_view, name="company_filter_view"),
    # path("reviews/filter/", views.review_filter_view, name="review_filter_view"),
]

Capstone/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('about/', views.about_view, name="about_view"),
    path('error/', views.not_found_view, name="not_found_view"),

]

Capstone/main/models.py
from django.db import models

# Create your models here.

Capstone/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse



# Create your views here.

def home_view(request : HttpRequest):

    return render(request, "main/index.html")


def about_view(request: HttpRequest):

    return render(request, "main/about.html")

def not_found_view(request: HttpRequest):

    return render(request, "main/about.html")

Capstone/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %} About  {% endblock %}


{% block content %}
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

    
<h class="some">test </h>
</div>


{% endblock %}

Capstone/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">        
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0,0" />
        <link href="https://fonts.googleapis.com/css2?family=Markazi+Text&family=Noto+Naskh+Arabic:wght@500&family=Readex+Pro:wght@300&display=swap" rel="stylesheet">

    </head>
    <style>
    body{
      background-image: linear-gradient(to right,#466A8B ,#AD9E8E);}
    .navbar{
      height: 96px;
      background-color: transparent;
      border: black;
      transition: background-color 0.3s;
    }
    #navbarsExample09{
      color: rgb(8, 10, 12);
      direction: rtl;
      font-size: 34px;
    }
    .navbar.scrolled {
      position: sticky;
      background-image: linear-gradient(to right,#466a8ba6 ,#ad9e8e91);
      border: 2px solid #c5ab9056; /* Add a 2px solid border with your desired color (#333 in this example) */
    }
    .nav-link{
      color: aliceblue;
      margin-left: 5px;
    }  
    .nav-link:hover{
      color: #C49D78;
      border-radius: 3%;
    }
    .nav-link::after{
      color: #C49D78;
      border-radius: 3%;
    }
    .form-control{
      opacity: .6; }
    .dropdown-menu{
      background-color: #acc8c7c2;
      font-size: 18px;
      font-weight: 600;

    }
    .search{
    background-image: url('/static/images/search.png');
    background-repeat: no-repeat;
    background-position: left center; /* Position the icon on the right */
}
.dropdown.clicked{
  color: #466A8B;
}
.navbar-brand{
  left: 90%;
}
.fixed {
    position: fixed;
    top: 0;
}
    </style>
 
        <nav class="navbar sticky-top navbar-expand-lg scroll" aria-label="Eleventh navbar example">
            <div class="container">
              <a class="navbar-brand fixd" style="color: aliceblue; font-size: 30px;" href="/"> <img src="{% static 'images/Removal-694.png' %}" style=" height:110px; margin-top: 7px;"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarsExample09">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class=" nav-link " aria-current="page" href="{% url 'main:home_view' %}">الرئيسية</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " href="#about">عنا </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " href="{% url 'companies:all_companies_view'%}">  الشركات</a>
                  </li>
                  
                  <li class="nav-item dropdown " >
                    <a class="nav-link " href="#" data-bs-toggle="dropdown" aria-expanded="false">
                     
                      {% if request.user.is_authenticated %}
                        <img src="{{ request.user.profile.avatar.url }}" alt="avatar" width="32" height="32" class="avatar rounded-circle">
                        {{ request.user.first_name }} <span class="material-symbols-outlined" style="align-items: center;font-size: large;">menu</span>
                      {% else %} 
                      <span class="material-symbols-outlined">account_circle</span> {% endif %} 
                    </a>
                    <ul class="dropdown-menu">
                      
                      {% if request.user.is_staff %}
                          <li><a class="dropdown-item" href="{% url 'companies:dashbord_view' request.user.id %}">لوحة التحكم<span class="material-symbols-outlined">dashboard</span></a></li>
                          <li><a class="dropdown-item" href="{% url 'companies:add_company_view' %}"> اضافة شركة<span class="material-symbols-outlined">edit_note</span></a></li> 
                          <li><a class="dropdown-item" href="{% url 'accounts:logout_user_view' %}">تسجيل الخروج <span class="material-symbols-outlined">logout</span></a></li>
                      {% endif %}
                      {% if request.user.is_authenticated and not request.user.is_staff  %}
                        <li><a class="dropdown-item" href="{% url 'accounts:profile_page' request.user.id %}">الملف الشخصي <span class="material-symbols-outlined">account_circle</span></a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:update_profile_page' request.user.id %}">تعديل معلوماتي <span class="  fa-fw material-symbols-outlined">settings</span></a></li>
                        <li><a class="dropdown-item" href="{% url 'companies:add_company_view' %}"> اضافة شركة<span class="material-symbols-outlined">edit_note</span></a></li> 
                        <li><a class="dropdown-item" href="{% url 'accounts:logout_user_view' %}">تسجيل الخروج <span class="material-symbols-outlined">logout</span></a></li>
                       {% elif not request.user.is_authenticated and not request.user.is_staff  %} 
                        <li><a class="dropdown-item" href="{% url 'accounts:login_user_view' %}"> التسجيل <span class="material-symbols-outlined">login</span> </a></li> 
                      {% endif %}              
                      </ul>
                  </li>
                </ul>
                <form role="search" action="{% url 'companies:companies_search_view' %}" method="get">
                <input  name="search" class="form-control search" aria-hidden="true" type="search" placeholder="  اسم الشركة.. " aria-label="Search">
                </form>
              </div>
            </div>
          </nav>
          
        <div class="container pt-2">

            {% block content %}

            {% endblock %}
            
        </div>
        <div class="container pt-5">
          <footer class="py-3 my-4">

            <ul class="nav justify-content-center border-bottom pb-3 mb-3 ">
              <li class="nav-item"><a href="/" class="nav-link px-2">الرئيسية</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 "> سياسة الخصوصية</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 ">شروط الاستخدام</a></li>
              <li class="nav-item"><a href="#" class="nav-link px-2 ">الأسئلة الشائعة</a></li>
              <li class="nav-item"><a href="#about" class="nav-link px-2 ">عننا</a></li>

            </ul>
            <p class="text-center text-body-secondary"> مرآه وظيفتي © 2023 </p>
          </footer>
        </div>
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <link rel="stylesheet" type="text/css" href="styles.css">
        <script src="main.js"></script>
        <script>
    
          const navbar = document.querySelector('.navbar');
          
          // Function to handle the scroll event
          function handleScroll() {
              if (window.scrollY > 100) {
                  // Add the "scrolled" class to the navbar when scrolling down
                  navbar.classList.add('scrolled');
              } else {
                  // Remove the "scrolled" class when at the top of the page
                  navbar.classList.remove('scrolled');
              }
          }
          
          // Attach the scroll event listener
          window.addEventListener('scroll', handleScroll);

          window.addEventListener("scroll", function () {
    const navbar = document.querySelector(".navbar");
    if (window.scrollY > navbar.offsetHeight) {
        navbar.classList.add("fixed");
    } else {
        navbar.classList.remove("fixed");
    }
});
            </script>
      </body>
        </html>

Capstone/main/templates/main/index.html
{% extends 'main/base.html' %}
{%load static %}

{% block title %} home {% endblock %}


{% block content %}
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>
<link href="https://fonts.googleapis.com/css2?family=Markazi+Text&family=Noto+Naskh+Arabic:wght@500&family=Readex+Pro:wght@300&display=swap" rel="stylesheet">
<style>
  body {
    overflow-x: hidden;
    margin: 0;
    padding: 0;
    background-image: linear-gradient(to right,#466A8B ,#AD9E8E);

}

body{
    font-family: 'Markazi Text', serif;
    background-color:#e8e8e8;
    

   }
      @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900);
      .contact-form {
      }
      .contact-form .input-block {
        background-color: rgba(255, 255, 255, 0.8);
        border: solid 1px #466A8B;
        width: 100%;
        height: 60px;
        padding: 25px;
        position: relative;
        margin-bottom: 20px;
        -moz-transition: all 0.3s ease-out;
        -o-transition: all 0.3s ease-out;
        -webkit-transition: all 0.3s ease-out;
        transition: all 0.3s ease-out;
      }
      .contact-form .input-block.focus {
        background-color: #fff;
        border: solid 1px #466A8B;
      }
      .contact-form .input-block.textarea {
        height: auto;
      }
      .contact-form .input-block.textarea .form-control {
        height: auto;
        resize: none;
      }
      .contact-form .input-block label {
        position: absolute;
        left: 25px;
        top: 25px;
        display: block;
        margin: 0;
        font-weight: 300;
        z-index: 1;
        color: #333;
        font-size: 18px;
        line-height: 10px;
      }
      .contact-form .input-block .form-control {
        background-color: transparent;
        padding: 0;
        border: none;
        -moz-border-radius: 0;
        -webkit-border-radius: 0;
        border-radius: 0;
        -moz-box-shadow: none;
        -webkit-box-shadow: none;
        box-shadow: none;
        height: auto;
        position: relative;
        z-index: 2;
        font-size: 18px;
        color: #333;
      }
      .contact-form .input-block .form-control:focus label {
        top: 0;
      }
      .contact-form .square-button {
        background-color: rgba(255, 255, 255, 0.8);
        color: #466A8B;
        font-size: 26px;
        text-transform: uppercase;
        font-weight: 700;
        text-align: center;
        -moz-border-radius: 2px;
        -webkit-border-radius: 2px;
        border-radius: 2px;
        -moz-transition: all 0.3s ease;
        -o-transition: all 0.3s ease;
        -webkit-transition: all 0.3s ease;
        transition: all 0.3s ease;
        padding: 0 60px;
        height: 60px;
        border: none;
        width: 100%;
      }
      .contact-form .square-button:hover, .contact-form .square-button:focus {
        background-color: white;
      }
      
      @media (min-width: 768px) {
        .contact-wrap {
          width: 60%;
          margin: auto;
        }
      }
      /*----page styles---*/
      body {
        background-color: rgb(217, 196, 170);
        background-color:#e8e8e8;
        transition: all 0.3s ease;


      }
      .contact-wrap {
        padding: 15px;
      }
      h1 {
        background-color: white;
        color: #466A8B;
        padding: 40px;
        margin: 0 0 30px;
        font-size: 30px;
        text-transform: uppercase;
        font-weight: 700;
        text-align: center;
      }
      .home{
        font-size: large;
        margin-right: 33px;
      }
      #name{
        font-size: 50px;
        color:#fff;
      }
     .homecontent{
      font-size: 35px;
      margin-top: 8%;
     }
     .img{
        width: 300px;
        height: auto;
     }
     #homepage{
      margin-top: 10%;
      height: 100vh;
     }
     .btn-3 {
    background: #466A8B;
    background: linear-gradient(0deg, #466A8B 0%, #729bc2 100%);
    width: 130px;
    height: 40px;
    line-height: 42px;
    padding: 0;
  }
  .btn-3 span {
    position: relative;
    display: block;
    width: 100%;
    height: 100%;
  }
  .btn-3:before,
  .btn-3:after {
    position: absolute;
    content: "";
    right: 0;
    top: 0;
     background: #466A8B;
    transition: all 0.3s ease;
  }
  .btn-3:before {
    height: 0%;
    width: 2px;
  }
  .btn-3:after {
    width: 0%;
    height: 2px;
  }
  .btn-3:hover{
    background: transparent;
    box-shadow: none;
  }
  .btn-3:hover:before {
    height: 100%;
  }
  .btn-3:hover:after {
    width: 100%;
  }
  .custom-btn {
    width: 30%;
    margin-left: 5px;
    margin-top: 30px;
    height: 45px;
    border: 0;
    outline: 0;
    color: white;
    font-size: 25px;
    font-weight: 400;
    position: relative;
    z-index: 3;
    background: #466A8B;
    font-family: 'Markazi Text', serif;
    box-shadow: 3px 3px 5px rgba(0, 0, 0, 0.3);
  }
   .homepage{
    margin-right: 55px;
   }
   #about{
    height:100vh;
    background-color: #d9c4aa60;
    width: 100%;
    border-radius: 3%;
    padding: 30px;
   }
  .abouthome{
    width: 40%;
  }
  .aboutcontent{
    font-size: 27px;
    font-weight: 600;
    height: auto;
    width: 100%;

  }
  #who{
    font-size: 90px;
    margin-left: 30% !important;
  }
.category{
  display: flex;
  flex-flow: column;
  justify-content: center;
  align-items: center;
  width: 200px;
  height: 200px;
  font-size: 30px;
  margin-top: 35% !important;
  row-gap: 25px;
  background-color:white;
  border-color: #30334B;
  box-shadow: #30334B;
  color: #30334B;
  transition: all 0.3s ease;
  border-radius: 3%;
}
.category:hover{
  background-color:#acc8c7a8;
  color: #fff;

}
.catgorypage{
  display: flex;
  height: 100vh;
  column-gap: 40px;
  margin-top: 5%;

}
.categoryhead{
  width: 100%;
  font-size: 45px;
  font: 700;
}

.child {
    animation-duration: 2s;
    animation-iteration-count: infinite;
    transform-origin: bottom;
}
.bounce:hover {
    animation-name: bounce;
    animation-timing-function: ease;
}
@keyframes bounce {
  0%   { transform: translateY(0); }
  50%  { transform: translateY(-50px); }
  100% { transform: translateY(0); }
}
.input-block{
  justify-content: start;
  
}
label{
  justify-content: start;
}
.head{
        margin-right: 40%;
        margin-bottom: 8%;
        font-size: 39px;
        font-weight: 600;
        color: rgb(7, 20, 77);
    }
</style>

<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
<section  id="homepage" >
<div class="row pt-4 homepage">
    <div class=" col-6 home">
        <div class="d-flex flex-row align-items-center ">
          <h4 id="name" class="animate__bounceIn animate__animated"  > مراَة وظيفتي</h4> 
           <p class="homecontent">   اتخذ قرارات مستنيرة حول أماكن العمل المحتملة </p>
          
          </div>
          <a id="explore" href="#cattop" class="btn btn-3 custom-btn page-scroll ">تصفح الشركات</a>  
          <a href="#abouttop"  class="btn btn-3 custom-btn page-scroll ">اعرف اكثر</a>  
          <div class="row">
              </div>
        </div>
        
<div class="col">
  <img src="{%static 'images/tl.webp'%}" class="animate__bounceInLeft animate__animated img" style="animation-duration: 2s;">

</div>
    </div>
  </section>
 <section id="abouttop" style="height: 60px;">

 </section>
<section id="about">
 
  <div class="row">
    <div class="col">
        <span id="who"> من نحن <span style="transform: scaleX(-1); font-size: 35px;" class="material-symbols-outlined">
          question_mark
          </span></span>
        <div class="aboutcontent">
        <div class=""> 
            المكان المثالي للعثور على المعلومات التي تحتاجها لاتخاذ قرارات مستنيرة بشأن مستقبلك المهني 
            <span id="name">"مراَة وظيفتي" </span>
          سواءًا كنت تبحث عن معلومات حول بيئة العمل أو ترغب في فهم كيفية الاستعداد لمقابلة وظيفية، نوفر لك المعلومات عن الشركات في كافة القطاعات ويمكن للموظفين السابقين الذين عاشوا تجارب مع هذه الشركات مشاركة تجاربهم وآرائهم بكل حرية. 
         <div class="animate__bounceInLeft animate__animated" style="animation-duration: 3s;">
         توجيه وتقديم نصائح:<br>
          يمكن للموظفين السابقين تقديم نصائح وتوجيهات للباحثين عن العمل حول كيفية التقديم للوظائف في تلك الشركات وكيفية النجاح في عمليات المقابلة.
         </div>
         
         <div class="animate__bounceInLeft animate__animated" style="animation-duration: 5s;">
         تحسين الشفافية:<br>
         نساعد على زيادة شفافية الشركات وتشجيعها على تحسين ظروف العمل وثقافتها الشركية.
         </div>
        </div>
    </div>
  </div></div>

</section>
<section id="cattop" style="height: 100px;">

</section>
<section id="catgorypage">
 <h2 id="categoryhead" class="categoryhead">تصنيفات الشركات</h2>
<div class="catgorypage">
<a style="text-decoration: none;" href="{% url 'companies:companies_search_view' %}?تقنية=تقنية" >
<button class="category child bounce">
  <span style="font-size: 50px;" class="material-symbols-outlined"> database</span>
  التقنية
   </button> 
  </a>
  <a  style="text-decoration: none;" href="{% url 'companies:companies_search_view' %}?صحي=صحي">
<button class="category child bounce">
  <span style="font-size: 50px;" class="material-symbols-outlined">ecg_heart</span>
  الصحة 
</button>
</a>
<a style="text-decoration: none;" href="{% url 'companies:companies_search_view' %}?الاتصالات=الاتصالات" >
<button class="category child bounce">
  <span style="font-size: 50px;" class="material-symbols-outlined">rss_feed</span>
  الاتصالات 
</button>
</a>
<a style="text-decoration: none;" href="{% url 'companies:companies_search_view' %}?البنوك=البنوك">
<button class="category child bounce"> 
   <span style="font-size: 50px;" class="material-symbols-outlined">account_balance</span>
  البنوك
</button>
</a>
<a style="text-decoration: none;" href="{% url 'companies:all_companies_view'%}">
<button class="category child bounce"> 
  <span style="font-size: 50px;" class="material-symbols-outlined">domain</span>
 كل القطاعات
</button>
</a>
</div>
</section>

<section id="contact">
  <h2 class="head animate__shakeY animate__animated" > تواصل معنا </h2>
  <section class="contact-wrap">
    <form action="" class="contact-form">
      <div class="col-sm-12">
        <div class="input-block">
          <label for="" aria-placeholder="">اسمك</label>
          <input type="text" class="form-control">
        </div>
      </div>
      <div class="col-sm-12">
        <div class="input-block">
          <label for="">البريد الالكتروني</label>
          <input type="text" class="form-control">
        </div>
      </div>
      <div class="col-sm-12">
        <div class="input-block textarea">
          <label for="">ملاحظاتك</label>
          <textarea rows="3" type="text" class="form-control"></textarea>
        </div>
      </div>
      <div class="col-sm-12">
        <button class="square-button">إرسال</button>
      </div>
    </form>
  </section>
</div>

</section>
  
  
<script>
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
      anchor.addEventListener('click', function(e) {
          e.preventDefault();

          const targetId = this.getAttribute('href').substring(1);
          const targetElement = document.getElementById(targetId);

          if (targetElement) {
              targetElement.scrollIntoView({
                  behavior: 'smooth',
                  block: 'start',
              });
          }
      });
  });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'styles/index.js' %}" ></script>

{% endblock %}

Capstone/main/templates/main/not_found.html
<div class="container">
    <style>
  @import url(https://fonts.googleapis.com/css?family=Gilda+Display);
  
  html {
  background: radial-gradient(#000, #111);
  color: white;
  overflow: hidden;
  height: 100%;
  user-select: none;
  }
  
  .static {
  width: 100%;
  height: 100%;
  position: relative;
  margin: 0;
  padding: 0;
  top: -100px;
  opacity: 0.05;
  z-index: 230;
  user-select: none;
  
  }
  
  .error {
  text-align: center;
  font-family: 'Gilda Display', serif;
  font-size: 95px;
  font-style: italic;
  text-align: center;
  width: 100px;
  height: 60px;
  line-height: 60px;
  margin: auto;
  position: absolute;
  top: 0;
  bottom: 0;
  left: -60px;
  right: 0;
  animation: noise 2s linear infinite;
  overflow: default;
  }
  
  .error:after {
  content: '404';
  font-family: 'Gilda Display', serif;
  font-size: 100px;
  font-style: italic;
  text-align: center;
  width: 150px;
  height: 60px;
  line-height: 60px;
  margin: auto;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  opacity: 0;
  color: blue;
  animation: noise-1 .2s linear infinite;
  }
  
  .info {
  text-align: center;
  font-family: 'Gilda Display', serif;
  font-size: 15px;
  font-style: italic;
  text-align: center;
  width: 200px;
  height: 60px;
  line-height: 60px;
  margin: auto;
  position: absolute;
  top: 140px;
  bottom: 0;
  left: 0;
  right: 0;
  animation: noise-3 1s linear infinite;
  }
  
  .error:before {
  content: '404';
  font-family: 'Gilda Display', serif;
  font-size: 100px;
  font-style: italic;
  text-align: center;
  width: 100px;
  height: 60px;
  line-height: 60px;
  margin: auto;
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  opacity: 0;
  color: red;
  animation: noise-2 .2s linear infinite;
  }
  
  @keyframes noise-1 {
  0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;}
  10% {opacity: .1;}
  50% {opacity: .5; left: -6px;}
  80% {opacity: .3;}
  100% {opacity: .6; left: 2px;}
  }
  
  @keyframes noise-2 {
  0%, 20%, 40%, 60%, 70%, 90% {opacity: 0;}
  10% {opacity: .1;}
  50% {opacity: .5; left: 6px;}
  80% {opacity: .3;}
  100% {opacity: .6; left: -2px;}
  }
  
  @keyframes noise {
  0%, 3%, 5%, 42%, 44%, 100% {opacity: 1; transform: scaleY(1);}  
  4.3% {opacity: 1; transform: scaleY(1.7);}
  43% {opacity: 1; transform: scaleX(1.5);}
  }
  
  @keyframes noise-3 {
  0%,3%,5%,42%,44%,100% {opacity: 1; transform: scaleY(1);}
  4.3% {opacity: 1; transform: scaleY(4);}
  43% {opacity: 1; transform: scaleX(10) rotate(60deg);}
  }
    </style>
  
  
  <div class="error">404</div>
  <br /><br />
  <span class="info">File not found</span>
  <img src="http://images2.layoutsparks.com/1/160030/too-much-tv-static.gif" class="static" />
  </div>