Capstone/Capstone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('companies/', include("companies.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Capstone/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_user_view, name="login_user_view"),
    path("register/", views.register_user_view, name="register_user_view"),
    path("logout/", views.logout_user_view, name="logout_user_view"),
    path('profile/<user_id>/', views.profile_page, name="profile_page"),
    path('profile/update/<user_id>/', views.update_profile_page, name="update_profile_page"),
    path('my_added_company/<user_id>/', views.added_company_list_view, name="added_company_list_view"),
]

Capstone/companies/urls.py
from django.urls import path
from . import views

app_name = "companies"

urlpatterns = [
     
    path("all/", views.all_companies_view, name="all_companies_view"),
    path("add/", views.add_company_view, name="add_company_view"),
    path("dashboard/<user_id>/",views.dashbord_view,name="dashbord_view"),
    path("update/<company_id>/", views.company_update_view, name="company_update_view"),
    path("delete/<company_id>/", views.company_delete_view, name="company_delete_view"),
    path("detail/<company_id>/", views.company_detail_view, name="company_detail_view"),
    path("search/",views.companies_search_view, name="companies_search_view"),
    path("approve/",views.approve_company_view, name="approve_company_view"),
    path("reveiw/add/<company_id>/",views.add_Review_view,name="add_Review_view"),
    path("reveiw/delete/<review_id>/",views.review_delete_view,name="review_delete_view"),
    path("reveiw/update/<review_id>/", views.review_update_view, name="review_update_view"),
    path("reveiw/all/", views.all_reveiws_view, name="all_reveiws_view"),
    path("favorite/add/<review_id>/", views.add_favorite_view, name="add_favorite_view"),
    path("favorite/delete/<review_id>/", views.remove_favorite_view, name="remove_favorite_view"),
    path("report/<review_id>/", views.report_view, name="report_view"),
    path("reports", views.all_report_view, name="all_report_view"),
    path("favorites/", views.user_favorite_view, name="user_favorite_view"),
    path("field/", views.company_filter_view, name="company_filter_view"),
    # path("reviews/filter/", views.review_filter_view, name="review_filter_view"),
]

Capstone/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('about/', views.about_view, name="about_view"),
    path('error/', views.not_found_view, name="not_found_view"),

]

Capstone/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.CharField(max_length=2048, blank=True)
    birth_date = models.DateField(default="1995-1-1")
    avatar = models.ImageField(upload_to="images/", default="images/default-avatar.png")
    twitter_link = models.URLField(blank=True)


    def __str__(self) -> str:
        return f"{self.user.username} profile"

Capstone/companies/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Company(models.Model):

    name = models.CharField(max_length=2048)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/")
    field = models.CharField(max_length=2048)
    info= models.TextField()
    description = models.TextField()
    publish_date = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

   
    def __str__(self):
        return f"{self.name}"
    

class Review(models.Model):

    rating_choices = ((1, "1 Star"), (2, "2 Stars"), (3, "3 Stars"), (4, "4 Start"), (5, "5 Start"), )
    experience_choices = (("موظف", "موظف"), ("مقابلة", "مقابلة"), ("تدريب", "تدريب"), )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company=models.ForeignKey(Company,on_delete=models.CASCADE)
    experience = models.CharField(max_length=128, choices=experience_choices)
    position = models.CharField(max_length=256)
    description = models.TextField()
    publish_date = models.DateField(auto_now_add=True)
    rating = models.IntegerField(choices=rating_choices)



    def __str__(self):
        return f"{self.user.first_name} on {self.company.name}"

class Favorite(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.review} on {self.review}"

class Report(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.review} on {self.review}"

Capstone/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.models import User
from .models import Profile
from companies.models import Company
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def register_user_view(request : HttpRequest):
     
    msgg = None

    if request.method == "POST":
        new_user = User.objects.create_user(first_name=request.POST["first_name"], last_name=request.POST["last_name"], username=request.POST["username"], email=request.POST["email"], password=request.POST["password"], )
        new_user.save()
        profile=Profile.objects.create(user=new_user)
        profile.save()
        msgg = " "
    
    return render(request, "accounts/registration.html", {"msgg": msgg})
    


def login_user_view(request: HttpRequest):

    msg = None

    if request.method == "POST":
        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])

        if user:
            login(request, user)
            return redirect("main:home_view")
        else:
            msg = "اسم المستخدم او كلمة المرور غير صحيحة"


    return render(request, "accounts/registration.html", {"msg": msg})



def logout_user_view(request: HttpRequest):

    logout(request)

    return redirect("accounts:login_user_view")

def profile_page(request:HttpRequest, user_id):

    try:
        profile = Profile.objects.get(user__id=user_id)
    except:
        return render(request, "main/not_found.html")

    return render(request, "accounts/profile.html", {"profile" : profile})

def update_profile_page(request:HttpRequest, user_id):

    try:
        user = User.objects.get(id=user_id)
        profile, is_created = Profile.objects.get_or_create(user=user)
    except:
        return render(request, "main/not_found.html")
    
    if request.method == "POST":
        profile.about = request.POST["about"]
        profile.twitter_link = request.POST["twitter_link"]
        profile.birth_date = request.POST["birth_date"]
        if "avatar" in request.FILES:
            profile.avatar = request.FILES["avatar"]
        profile.save()

        return redirect("accounts:profile_page", user_id=user_id)
        
    return render(request, "accounts/update_profile.html", {"profile" : profile})

def added_company_list_view(request,user_id ):
    companies = Company.objects.filter(id=user_id)


    return render(request, 'accounts/my_added_company.html', {'companies': companies})

Capstone/accounts/templates/accounts/my_added_company.html
{% extends 'main/base.html'%}


{% block title %} {{profile.user.username}} الملف الشخصي {% endblock %}

{% block content %}

<style>

body{
    direction: rtl;
    }
h1{
    margin-top: 5%;
    margin-bottom: 5%;
    color: #30334B;
}
table th{
    color:#C49D78 ;
}

.material-symbols-outlined {
  font-variation-settings:
  'FILL' 1,
  'wght' 400,
  'GRAD' 0,
  'opsz' 24
}


    
</style>


{% if "msg" in  request.GET %}
    <strong>{{request.GET.msg}}</strong>
{% endif %}
       
        <div class="border border-light p-2 mb-2 text-center p-4 mt-4  "> <h2 style="color: #30334B;" > الشركات المضافة</h2></div>

        
        <table class="table  table-secondary  table-opacity-75 ">
            <thead>
                <tr>
                    <th scope="col "> </th>
                    <th scope="col">اسم الشركة</th>
                    <th scope="col">مجالها</th>
                    <th scope="col">الحاله</th>
                </tr>
            </thead>
            
            <tbody>
                
                {% for company  in request.user.company_set.all %}
        <tr>
            <th scope="row ">-
            <td>{{ company.name }}</td>
            <td>{{ company.info }}</td>
            <td> {% if company.approved %}
                <p> <i class="material-symbols-outlined text-success">Circle</i> مقبول  </p>
            {% else %}
                <p> <i class="material-symbols-outlined text-danger">Circle</i> بالإنتظار  </p>
            {% endif %}</td></th>

        </tr>
        </tbody>
        {% endfor %}
    </table>

    <a href="{% url 'accounts:profile_page' request.user.id %}" class="btn btn-color mt-4 "> <span class="material-symbols-outlined">
        arrow_forward_ios
        </span>رجوع</a>
{% endblock %}

Capstone/accounts/templates/accounts/profile.html
{% extends 'main/base.html' %}

{% block title %} {{profile.user.username}} الملف الشخصي  {% endblock %}


{% block content %}

<style>

body{
    direction: rtl;
  }
  
.material-symbols-outlined {
  font-variation-settings:
  'FILL' 0,
  'wght' 400,
  'GRAD' 0,
  'opsz' 24
}
    .dashboard {
  grid-template-rows: 50% 50%;
  height: calc(100vh - 90px);
  margin-top: 25px;
}
.dashboard .main {
  grid-row: 1 / span 2;
  grid-column: 1 / span 1;

  
}
.dashboard .description {
  grid-row: 1 / span 2;
  grid-column: 2 / span 3;

}
.dashboard-card {
  background: white;
  box-shadow: 0 0 10px rgba(0,0,0,0.2);
  padding: 50px;
  margin: 20px;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: space-around;
}
@media (max-width: 992px) {
  .dashboard {
    display: block;
  }
}

/* Fonts and colors */
.dashboard h2 {
  font-size: 20px;
}
.dashboard h3 {
  color: #37B686;
  font-size: 25px;
  margin-bottom: 15px;
}
.dashboard p {
  color: rgba(0,0,0,0.5);
  font-size: 16px;
}
.dashboard img {
  margin-top: 10px;
  border-radius: 10%;
  margin-bottom: 10px;
 
}

.dashboard .btn:hover {
  background: #37B686;
  opacity: 0.7;
}
.main p {
  margin-bottom: 30px;
}


</style>

      <div class="container">
        <div class="border border-light p-2 mb-2 text-center p-4 mt-4"> <h2 style="color: #30334B;" >الملف الشخصي </h2></div>

        <div class="dashboard">
          <div class="dashboard-card main">
            <div class="dashboard-card-content">
              <img src="{{profile.avatar.url}}"width="100" >  
              <h2>{{profile.user.first_name}} {{profile.user.last_name}}</h2> 
              <p>{{profile.about}}</p>
              <a href="{% url 'accounts:update_profile_page' request.user.id %}"><i class="material-symbols-outlined">Settings</i></a>
            </div>
          </div>
       
          <div class="dashboard-card description">
              <div class="dashboard-card-content">

                 <nav class="navbar navbar-expand-lg navbar-light">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                      <ul class="navbar-nav ">
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'companies:all_reveiws_view' %}"> التعليقات  <i class="material-symbols-outlined">Comment</i></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link"  href="{% url 'companies:user_favorite_view' %}">الاعجابات <i class="material-symbols-outlined">Favorite</i></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link " href="{% url 'accounts:added_company_list_view' user.id %}">الشركات المضافه<i class="material-symbols-outlined">Domain</i></a>
                        </li>
                      </ul>
                    </div>
                  </nav>
               </div>
            
          </div>
      
        </div>

      </div>



{% endblock %}

Capstone/accounts/templates/accounts/registration.html
{% extends 'main/base.html' %}
{%load static %}

{% block title %} User Registeration  {% endblock %}


{% block content %}
 <style>

@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400");
@import url("https://fonts.googleapis.com/css?family=Playfair+Display");
@import url('https://fonts.googleapis.com/css2?family=Markazi+Text:wght@400;500&family=Noto+Naskh+Arabic:wght@500&family=Readex+Pro:wght@300&display=swap');

.message,
.container-signup .form,
.container-signup form {
  
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}

body{
  direction: rtl;
  font-family: 'Markazi Text', serif;

}
.navbar-brand{
  direction: rtl;

}
.form input {
direction: rtl;
}
.container-signup {
  direction: ltr;
  margin-top: 10%;
  width: 100%;
  height: 400px;
  background: white;
  position: relative;
  display: grid;
  grid-template: 100%/50% 50%;
  box-shadow: 2px 2px 10px 0 rgba(51, 51, 51, 0.2);
}

.container-signup .message {
  position: absolute;
  background: white;
  width: 50%;
  height: 100%;
  transition: 0.5s all ease;
  transform: translateX(100%);
  z-index: 4;
}
.container-signup .message:before {
  position: absolute;
  content: "";
  width: 1px;
  height: 70%;
  background: #c3c3d8;
  opacity: 0;
  left: 0;
  top: 15%;
}
.message .button {
  margin: 5px 0;
}

.signup:before {
  opacity: 0.3;
  left: 0;
}

.login:before {
  opacity: 0.3;
  left: 100%;
}

.btn-wrapper {
  width: 60%;
}

.container-signup .form {
  width: 100%;
  height: 100%;
}
.container-signup .form--heading {
  font-size: 25px;
  height: 50px;
  color: #30334B;
  font-family: "Source Sans Pro", sans-serif;
}
.container-signup .form--signup {
  border-right: 1px solid #999;
}

.container-signup form {
  width: 70%;
}
.container-signup form > * {
  margin: 10px;
}
.container-signup form input {
  width: 90%;
  border: 0;
  border-bottom: 1px solid #aaa;
  font-size: 15px;
  font-weight: 300;
  color: #797a9e;
 
}
.container-signup form input::placeholder {
  color: #333;
  font-size: 10px;
}
.container-signup form input:focus {
  outline: 0;
  border-bottom: 1px solid rgba(128, 155, 206, 0.7);
  transition: 0.6s all ease;
}

.msg{
    font-size: 15px;
}
.container-signup .button {
  width: 100%;
  height: 30px;
  border: 0;
  outline: 0;
  color: white;
  font-size: 15px;
  font-weight: 400;
  position: relative;
  z-index: 3;
  background: #30334B;
  font-family: "Source Sans Pro", sans-serif;
  cursor: pointer;
}
 </style>

<div class="container-signup">
    <div class="message signup">
      <div class="btn-wrapper">
        <button class="button" id="signup">التسجيل  </button>
        <button class="button" id="login"> تسجيل الدخول</button>
      </div>
    </div>
    <div class="form form--signup">
      {% if msg %} 
        <h5 class=" msg text-white bg-white p-3 .message .button ">{{msgg}}</h5>
         {% endif %}
      <div class="form--heading">مرحبا! تسجيل مستخدم جديد</div>
      <form action="{% url 'accounts:register_user_view' %}" method="post" >
        {% csrf_token %}
        <input type="text" style="color: black;" name="first_name" class="form-control mt-2" placeholder="الاسم الاول" />
        <input type="text" name="last_name" class="form-control mt-2" placeholder="الاسم الاخير" />
        <input type="text" name="username" class="form-control mt-2" placeholder="اسم المستخدم" />
        <input type="email" name="email" class="form-control mt-2" placeholder="البريد الالكتروني" />
        <input type="password" name="password" class="form-control mt-2" placeholder="كلمة المرور" />
        <button class="button" type="submit" value="Register" >تسجيل</button>
      </form>
    </div>
    <div class="form form--login">
        {% if msg %} 
        <h5 class=" msg text-white bg-danger p-3 .message .button ">{{msg}}</h5>
         {% endif %}
      <div class="form--heading">مرحبا بعودتك! </div>
    
      <form action="{% url 'accounts:login_user_view' %}" method="post" >
        {% csrf_token %}
        <input type="text" name="username" class="form-control mt-2" placeholder="اسم المستخدم" />
        <input type="password" name="password" class="form-control mt-2" placeholder="كلمة المرور" />
        <button class="button" value="Login " type="submit">دخول</button>
      </form>
    </div>



</div>
  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'styles/js/main.js' %}" ></script>

{% if msg %}
<script>
    document.getElementById("login").click();
</script>
{% endif %}

{% if msgg %}
<script>
    document.getElementById("login").click();
</script>
{% endif %}


{% endblock %}

Capstone/accounts/templates/accounts/update_profile.html
{% extends 'main/base.html' %}
{%load static %}


{% block title %} About  {% endblock %}


{% block content %}
<style>

@import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400");
@import url("https://fonts.googleapis.com/css?family=Playfair+Display");


.container-signup .form,
.container-signup form  {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
}




.container-signup {
 margin-right: 20%;
  margin-top: 5%;
  padding: 10px;
  width: 800px;
  height: 600px;
  background: white;
  position: relative;
  display: grid;
  box-shadow: 2px 2px 10px 0 rgba(51, 51, 51, 0.2);
}



.container-signup .form--heading {
  font-size: 25px;
  height: 50px;
  color: #30334B;
  font-family: "Source Sans Pro", sans-serif;
}


.container-signup form  {
  width: 50%;
}
.container-signup form > * {
  margin: 10px;
}
.container-signup form input {
  width: 90%;
  font-size: 13px;
  font-weight: 300;
  color: #797a9e;
  letter-spacing: 0.11em;
}
.container-signup form input::placeholder {
  color: #333;
  font-size: 10px;
}
.container-signup form input:focus {
  outline: 0;
  border-bottom: 1px solid rgba(128, 155, 206, 0.7);
  transition: 0.6s all ease;
}

.container-signup .button {
  width: 50%;
  margin-top: 10%;
  height: 30px;
  border: 0;
  outline: 0;
  color: white;
  font-size: 15px;
  font-weight: 400;
  position: relative;
  z-index: 3;
  background: #30334B;
  font-family: "Source Sans Pro", sans-serif;
  cursor: pointer;
}
label{
    
    margin-left: 70% !important;
    margin-bottom: -30px !important;
    width: 80px;

}
</style>
<div class="container-signup">
 <div class="form form--signup ">
    <div class="form--heading"> تحديث الملف الشخصي   </div>
    <form action="{% url 'accounts:update_profile_page' profile.user.id %}" enctype="multipart/form-data"  method="post">
      {% csrf_token %}
      <label  class="form-label"  >نبذه عني  </label><br>
      <input id="floatingInput"  name="about" class="form-control " value="{{profile.about}}" />
      <label  class="form-label"  >تاريخ ميلادي  </label><br>
      <input   id="datePicker"  class="form-control mt-2"  type="date" class="form-control" id="floatingInput"  name="birth_date" value="{{profile.birth_date.isoformat}}"/>
      <label  class="form-label"  > حساب تويتر </label><br>
      <input type="url" class="form-control" id="floatingInput" name="twitter_link" value="{{profile.twitter_link}}" class="form-control mt-2"/>
      <label  class="form-label"  >الصوره الحاليه</label><br>
      {% if profile.avatar %}
      <img src="{{profile.avatar.url}}" class="avatar-big " style="height: 80px; width: 80px; " />
    {% endif %}
      <input type="file" accept="image/png, image/jpg" class="form-control" id="floatingAvatar" name="avatar" class="form-control mt-2"  />
      <button class="button" type="submit"  >تحديث</button>
    </form>
    <script>
      // Get the date input element
      var datePicker = document.getElementById("datePicker");

      // Get today's date in the format yyyy-mm-dd
      var today = new Date().toISOString().split("T")[0];

      // Set the maximum date for the date input field
      datePicker.setAttribute("max", today);
  </script>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="{% static 'styles/a.js' %}" ></script>

{% endblock %}